#include <opus/opus.h>

#define APPLICATION_NAME "Ongaku"
#define MAX_CLIENTS 64
#define HANDSHAKE_RETRY 5
#define SOCKET_BUFSIZE 32768
#define FRAGMENT_SIZE 960

#define FRAME_OPUS_DURATION 0.02
#define FRAME_SERVER_BUFFER_DURATION 0.25
#define FRAME_CLIENT_BUFFER_DURATION 0.25

#define OPUS_APPLICATION OPUS_APPLICATION_RESTRICTED_LOWDELAY

#define STREAM_TIMEOUT_SECONDS 30
#define HEARTBEAT_INTERVAL_SECONDS 10
